# Generated by Django 5.1.6 on 2025-02-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbudget',
            name='dietary_preference',
            field=models.CharField(max_length=50),
        ),
    ]
