# Generated by Django 5.1.6 on 2025-02-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_userbudget_dietary_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('cost', models.FloatField()),
                ('dietary_preference', models.CharField(max_length=50)),
            ],
        ),
    ]
